import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";
import { Navbar } from "./components/NavBar";
import { ForumSidebar } from "./components/SideNavBar";
import { SidebarProvider } from "@/providers/SideNavBarProvider";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthSessionProvider>
          <SidebarProvider>
            <Navbar></Navbar>
            <div className="flex">
              <ForumSidebar></ForumSidebar>
              <main className="flex-1 mt-16 md:ml-0">{children}</main>
            </div>
            <Toaster />
          </SidebarProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
